# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v3.4.0"
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/hakancelik96/unimport
    rev: stable
    hooks:
      - id: unimport
        args:
          [
            --remove,
            --include-star-import,
            --ignore-init,
            --gitignore,
          ]

  - repo: https://github.com/psf/black
    rev: "20.8b1"
    hooks:
      - id: black
        name: black
        description: A formatter for Python files
        files: \.py$

  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort
        description: isort your imports, so you don't have to.
        files: \.py$

  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.0"
    hooks:
      - id: flake8
        name: flake8
        description: Your Tool For Style Guide Enforcement
        files: \.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.812"
    hooks:
      - id: mypy
        name: mypy
        description: Optional Static Typing for Python
        files: \.py$

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
